package com.comp5348.store.fulfillment.service;

import com.comp5348.delivery.service.DeliveryService;
import com.comp5348.store.fulfillment.model.Fulfillment;
import com.comp5348.store.fulfillment.model.Fulfillment.AllocationEmb;
import com.comp5348.store.fulfillment.model.Fulfillment.Status;
import com.comp5348.store.fulfillment.repository.FulfillmentRepository;
import com.comp5348.store.inventory.service.InventoryService;
import com.comp5348.store.inventory.service.InventoryService.Allocation;
import com.comp5348.store.order.model.Order;
import com.comp5348.store.order.repository.OrderRepository;
import jakarta.transaction.Transactional;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Fulfillment business Logic:
 * Collaborate with Order, Inventory, Delivery Service
 */
@Service
public class FulfillmentService {

    private final FulfillmentRepository fulfillmentRepository;
    private final OrderRepository orderRepository;
    private final InventoryService inventoryService;
    private final DeliveryService deliveryService;

    public FulfillmentService(FulfillmentRepository fulfillmentRepository, OrderRepository orderRepository,
                              InventoryService inventoryService, DeliveryService deliveryService) {
        this.fulfillmentRepository = fulfillmentRepository;
        this.orderRepository = orderRepository;
        this.inventoryService = inventoryService;
        this.deliveryService = deliveryService;
    }

    /**
     * Reserve the stock and create the Fulfillment entity with RESERVED status
     * orderId       target order id
     * shipAddress   shipping address (used later when creating Delivery)
     * productId     product to reserve
     * quantity      requested quantity
     * created Fulfillment in RESERVED state with allocation snapshots
     */
    @Transactional
    public Fulfillment reserve(UUID orderId, String shipAddress, Long productId, int quantity) {
        // 1. Ensure order exists
        Order order = orderRepository.findById(orderId).orElseThrow(() -> new IllegalArgumentException("Order not found: " + orderId));

        //2. Try to allocate from inventories
        Optional<List<Allocation>> planOpt = inventoryService.reserveProduct(productId, quantity);
        if (planOpt.isEmpty()) {
            //Reservation failed
            throw new IllegalStateException("Insufficient stock for product: " + productId + "(qty=" + quantity + ")");
        }
        List<Allocation> plan = planOpt.get();

        //3. Create fulfillment aggregate, snapshot allocations
        Fulfillment fu = new Fulfillment(order, shipAddress);
        List<AllocationEmb> snaps = new ArrayList<>();
        for (Allocation al : plan) {
            snaps.add(new AllocationEmb(al.warehouseId, al.productId, al.quantity));
        }
        fu.setAllocations(snaps);
        fu.markReserved();

        //4.Persist
        return fulfillmentRepository.save(fu);
    }

    /**
     * Change to COMMITTED status and commit inventory reservation, create delivery
     * fulfillmentId id of fulfillment to commit
     * return true if committed, false if not found or invalid state
     */
    @Transactional
    public boolean commit(Long fulfillmentId) {
        Optional<Fulfillment> opt = fulfillmentRepository.findById(fulfillmentId);
        if (opt.isEmpty()) {
            return false;
        }
        Fulfillment fu = opt.get();
        if (fu.getStatus() != Status.RESERVED) {
            //Only RESERVED can be COMMITTED
            return false;
        }

        //1. Rebuild Allocation list from snapshot stored in Fulfillment
        List<Allocation> allocations = toAllocations(fu.getAllocations());

        //2. Commit reservations in Inventory
        boolean committed = inventoryService.commitReservation(allocations);
        if (!committed) {
            //if inventory commit fails, do not proceed
            return false;
        }

        //3. Create deliveries
        for (Allocation al : allocations) {
            //trackingNumber can be generated by an external system
            deliveryService.createDelivery(
                    fu.getOrder().getOrderId(), al.warehouseId, fu.getAddress(), null
            );
        }

        //4. Mark fulfillment committed
        fu.markCommitted();
        fulfillmentRepository.save(fu);
        return true;
    }

    /**
     * Back to CANCEL status and release inventory reservation
     * fulfillmentId id to cancel
     * return true if cancelled, false if not found or invalid state
     */
    @Transactional
    public boolean cancel(Long fulfillmentId) {
        Optional<Fulfillment> opt = fulfillmentRepository.findById(fulfillmentId);
        if (opt.isEmpty()) {
            return false;
        }

        Fulfillment fu = opt.get();
        if (fu.getStatus() != Status.RESERVED) {
            //Only RESERVED can be cancelled
            return false;
        }

        //Release inventory
        List<Allocation> allocations = toAllocations(fu.getAllocations());
        boolean released = inventoryService.releaseReservation(allocations);
        if (!released) {
            return false;
        }

        fu.markCancelled();
        fulfillmentRepository.save(fu);
        return true;
    }

    /** fetch all fulfillments for a given order id */
    @Transactional(Transactional.TxType.SUPPORTS)
    public List<Fulfillment> listByOrderId(UUID orderId) {
        return fulfillmentRepository.findByOrder_OrderId(orderId);
    }

    /** Lightweight existence check for order's fulfillment */
    @Transactional(Transactional.TxType.SUPPORTS)
    public boolean hasFulfillmentForOrder(UUID orderId) {
        return fulfillmentRepository.existsByOrder_OrderId(orderId);
    }

    //helpers
    private static List<Allocation> toAllocations(List<AllocationEmb> snaps) {
        List<Allocation> list = new ArrayList<>();
        for (AllocationEmb em : snaps) {
            list.add(new Allocation(em.warehouseId, em.productId, em.quantity));
        }
        return list;
    }
}